---
kind: pipeline
name: python27

steps:
- name: test
  image: python:2.7-alpine3.8
  commands:
    - ./drone.sh
    - pytest -c pytest_legacy.ini

---
kind: pipeline
name: python35

steps:
- name: test
  image: python:3.5-alpine3.8
  commands:
    - ./drone.sh
    - pytest -c pytest_legacy.ini

---
kind: pipeline
name: python36

steps:
- name: test
  image: python:3.6-alpine3.8
  commands:
    - ./drone.sh
    - pytest

---
kind: pipeline
name: python37

steps:
- name: test
  image: python:3.7-alpine3.8
  commands:
    - ./drone.sh
    - pytest
